# Tensors

In [1]:
import torch
import numpy as np

print(f"{torch.cuda.is_available()=}")
# print(f"{torch.accelerator.is_available()=}") # Not available due to old version of PyTorch
tensor = torch.rand((5, 3))
print(tensor)
print(f"tensor is stored on: {tensor.device}")

torch.cuda.is_available()=False
tensor([[0.7699, 0.1920, 0.9073],
        [0.1630, 0.6050, 0.9756],
        [0.3958, 0.9870, 0.0891],
        [0.6013, 0.0959, 0.5213],
        [0.0496, 0.8285, 0.9672]])
tensor is stored on: cpu


## Initializing a Tensor

Tensors can be initialized in various ways.

### Directly From Data

Data type is inferred.

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### From a NumPy Array

Tensors can be created from NumPy arrays (and vice versa)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

### From Another Tensor

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden

In [4]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8753, 0.3438],
        [0.7057, 0.0459]]) 



### With Random or Constant Values

`shape` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [5]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5169, 0.4529, 0.2234],
        [0.8568, 0.9959, 0.5024]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [6]:
tensor = torch.rand((3, 4))

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using the `.to()` method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [7]:
# # We move our tensor to the current accelerator if available
# if torch.accelerator.is_available():
#     tensor = tensor.to(torch.accelerator.current_accelerator())

### Standard NumPy-Like Indexing and Slicing:

In [8]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")  # : applies to exactly one dimension
print(f"Last column: {tensor[..., -1]}")  # ... applies to however many : are missing (equiv. to : in this case)
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concatenation

You can use `torch.cat()` to concatenate a sequence of tensors along a given dimension. See also `torch.stack()`, another tensore-joining operator that is subtly different from `torch.cat()`

In [9]:
t0 = torch.cat([tensor, tensor, tensor], dim=0)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"{t0}\n")
print(f"{t1}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithmetic Operations

In [10]:
print(tensor)
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T  # @ is the matrix multiplication operator
y2 = tensor.matmul(tensor.T)  # matrix multiplication
y3 = torch.rand_like(y1)  # creates a new tensor with the same shape and dtype as y1 but with random numbers sampled uniformly from [0,1)
torch.matmul(tensor, tensor.T, out=y3)  # out=y3 tells matmul to store the output in y3

print(y1)
print(y2)
print(y3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


### Single-Element Tensors

If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a python numerical value using `item()`

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### In-Place Operations

Operations that store the result into the operand are called in-place. They are denoted by a `_` suffix.

In [12]:
print(f"{tensor} \n")
tensor.add(5)
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### NOTE

In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

## Bridge with NumPy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

### Tensor to NumPy Array

In [13]:
t = torch.ones(5)
n = t.numpy()
print(f"{t=}")
print(f"{n=}")

t=tensor([1., 1., 1., 1., 1.])
n=array([1., 1., 1., 1., 1.], dtype=float32)


A change in the tensor reflects in the NumPy array.

In [14]:
t.add_(1)
print(f"{t=}")
print(f"{n=}")

t=tensor([2., 2., 2., 2., 2.])
n=array([2., 2., 2., 2., 2.], dtype=float32)


### NumPy Array to Tensor

In [15]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"{n=}")
print(f"{t=}")

n=array([1., 1., 1., 1., 1.])
t=tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Changes in the NumPy array reflects in the tensor

In [16]:
np.add(n, 1, out=n)
print(f"{n=}")
print(f"{t=}")

n=array([2., 2., 2., 2., 2.])
t=tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
